# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f66bc96bc8af32da33b15ce0cd6e29c33485fa81364b962cbc981167f412999aec0240f0cf9f8c6992e57e26c115c39f85831dd0902157148b19d671d57f2f9b

test:
  secret_key_base: 92fa296e68c63f42267c813e3329e7f000abda00bab2b3dee1fc4f835fc35edf1740db46d6d0a76ef3f89b2ff57ca93cce54e6e0a6ffbf8629c90d8c681409b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
